name: ActiveLife Chropractic
favicon: null
layout_spectrum: 0.9194966084323823
typography_spectrum: 0.000003948342055082321
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2563799717463553
  lightness: 0.7983725424855947
  saturation: 0.6930935001000762
  rhythmicContrast: 0.9596293792128563
purpose: []
